service:
  name: "NGINX redactor"
  description: "Service that takes logs from NGINX, anonymizes and offers them through an ELK stack."
  version: "0.1.0"
  validFor:
    startDate: "25/03/2024 10:33"
    endDate: "25/03/2044 10:33"
  characteristics:
  - name: "IP anonymization" 
    description: "Whether to redact the IP addresses of clients of the NGINX server."
    default: true
  - name: "VLD1 network"
    description: "The network used by VLD1."
    default: "192.168.1.0/24"
    whatToMove:
      values: ["192.168.1.0/24", "192.168.4.0/24"]
    whenToMove:
      periodic:
        value: 60
        unit: "min"
    howToMove: "uniform"
  - name: "VLD2 network"
    description: "The network used by VLD2."
    default: "192.168.2.0/24"
    whatToMove:
      values: ["192.168.2.0/24", "192.168.6.0/24"]
    whenToMove:
      periodic:
        value: 60
        unit: "min"
    howToMove: "uniform"
  - name: "VLD3 network"
    description: "The network used by VLD3."
    default: "192.168.3.0/24"
    whatToMove:
      values: ["192.168.3.0/24", "192.168.8.0/24"]
    whenToMove:
      periodic:
        value: 60
        unit: "min"
    howToMove: "uniform"
  - name: "NGINX-Classifier syslog port"
    description: "The port used for syslog between the NGINX VNF and the Privacy Classifier VNF."
    default: 514
    whatToMove:
      start: 514
      end: 10513
    whenToMove:
      periodic:
        value: 2
        unit: "min"
    howToMove: "normal"
  - name: "Classifier-Redactor syslog port"
    description: "The port used for syslog between the Privacy Classifier VNF and the Log Redactor VNF."
    default: 10514
    whatToMove:
      start: 10514
      end: 11000
    whenToMove:
      periodic:
        value: 3
        unit: "min"
    howToMove: "normal"
  - name: "Syslog protocol"
    description: "The protocol used for syslog, when applicable."
    default: "TCP"
    whatToMove:
      values: ["TCP", "UDP"]
    whenToMove:
      periodic:
        value: 120
        unit: "min"
    howToMove: "uniform"
  - name: "ELK user"
    description: "The user with superuser privileges to the ELK stack."
    default: "privacy_logger"
  - name: "NGINX VM image"
    description: "The image used by the VNF running the NGINX server."
    default: "rigourous-ubuntu"
    whatToMove:
      values: ["rigourous-ubuntu", "ubuntu20.04", "ubuntu22.04", "centos"]
    whenToMove:
      periodic:
        value: 1440
        unit: "min"
    howToMove: "sequential"
  - name: "Privacy Classifier VM image"
    description: "The image used by the VNF running the Privacy Classifier."
    default: "rigourous-ubuntu"
    whatToMove:
      values: ["rigourous-ubuntu", "ubuntu20.04", "ubuntu22.04", "centos"]
    whenToMove:
      periodic:
        value: 1440
        unit: "min"
    howToMove: "sequential"
  - name: "Log Redactor VM image"
    description: "The image used by the VNF running the Log Redactor."
    default: "rigourous-ubuntu"
    whatToMove:
      values: ["rigourous-ubuntu", "ubuntu20.04", "ubuntu22.04", "centos"]
    whenToMove:
      periodic:
        value: 1440
        unit: "min"
    howToMove: "sequential"
  - name: "Log Collector VM image"
    description: "The image used by the VNF running the Log Collector."
    default: "rigourous-ubuntu"
    whatToMove:
      values: ["rigourous-ubuntu", "ubuntu20.04", "ubuntu22.04", "centos"]
    whenToMove:
      periodic:
        value: 1440
        unit: "min"
    howToMove: "sequential"
