apiVersion: v1
kind: ConfigMap
metadata:
  name: janus-conf
data:
  janus.jcfg: |
    {{- include "demo.janusJcfg" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janus-settings
data:
  settings.js: |
    {{- include "demo.janusSettings" . | nindent 4 }}
