apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webrtc.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.webrtc.http }}
      targetPort: {{ .Values.webrtc.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.webrtc.ws }}
      targetPort: {{ .Values.webrtc.ws }}
      protocol: TCP
      name: ws
  selector:
    rigourous.service: {{ .Values.webrtc.name }}
