apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  logstash.conf: |
    {{- include "demo_broker.logstashConf" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-conf
data:
  logstash.yml: |
    {{- include "demo_broker.logstashYml" . | nindent 4 }}
