apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.broker.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.broker.port.value }}
      targetPort: {{ .Values.broker.port.value }}
      protocol: TCP
      name: {{ .Values.broker.port.name }}
  selector:
    rigourous.service: {{ .Values.broker.name }}
