apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.broker.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mutation.port }}
      targetPort: 1883
      protocol: TCP
      name: {{ .Values.broker.name }}
  selector:
    rigourous.service: {{ .Values.broker.name }}
