apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      rigourous.service: {{ .Values.nginx.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        rigourous.service: {{ .Values.nginx.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      containers:
        - name: {{ .Values.nginx.name }}
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.ports.http }}
              protocol: TCP
          {{- with .Values.nginxVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nginxVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webrtc.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      rigourous.service: {{ .Values.webrtc.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        rigourous.service: {{ .Values.webrtc.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demo.serviceAccountName" . }}
      containers:
        - name: "{{ .Values.webrtc.name }}"
          image: "{{ .Values.webrtc.repository }}"
          imagePullPolicy: {{ .Values.webrtc.pullPolicy }}
          ports:
            - name: {{ .Values.webrtc.port.name }}
              containerPort: {{ .Values.webrtc.port.value }}
          volumeMounts:
          {{- with .Values.webrtcVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.sharedVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: "{{ .Values.logstash.name }}"
          image: "{{ .Values.logstash.repository }}:{{ .Values.logstash.tag }}"
          imagePullPolicy: {{ .Values.logstash.pullPolicy }}
          volumeMounts:
          {{- with .Values.logstashVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.webrtcVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.logstashVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sharedVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
