apiVersion: v1
kind: ConfigMap
metadata:
  name: main
data:
  main.py: |
    {{- .Files.Get "files/main.py" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: update-nginx-conf
data:
  update-nginx-conf.sh: |
    {{- tpl (.Files.Get "files/update-nginx-conf.sh") . | nindent 4 }}
