apiVersion: v1
kind: ConfigMap
metadata:
  name: main
data:
  main.py: |
    {{- .Files.Get "files/main.py" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    {{- tpl (.Files.Get "files/nginx.conf") . | nindent 4 }}
