apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nginx_proxy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "nginx_proxy.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "nginx_proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
